### PR TITLE
APIBot: SDK update based on recent changes in Atlas API

### PR DESCRIPTION
**Pull request by wtrocki**
**Context**: An ongoing issue is preventing us from fetching openapi using URL. We going to work on the issue but we can unblock the release by this PR containing manual bot updates.

Additional changes to the typical bot PR:

- 72978d6ceb3a09e3b9da9564795cac893a3f5750 - Added transformation that removes pretty/envelope. (required if we use OpenAPI from the docs.
- [2a201ff](https://github.com/mongodb/atlas-sdk-go/pull/177/commits/2a201fff896abe166a1a5c6b83ce926afa0ba193) regenerated SDK. Contains the diff of the changes
- Added manual bump including breaking changes in the release.
---

Automatic update for MongoDB Atlas Go Client based on OpenAPI changes.
PR contains autogenerated changes for the MongoDB Atlas client.

## Automated checks

1. Compilation and unit tests
2. Documentation style
3. Transformation engine linting

## Important Details

1. If build is failing please check the logs and fix the issues in the OpenAPI file (openapi/atlas-api.yaml)
2. Do not attempt to manually fix any issues in the Golang Codebase as all changes are automatically generated. 
Fixes should be applied to the OpenAPI file (openapi/atlas-api.yaml) or ./tools engine in separate PR.

## Manual Review Procedure

1. Review changes in the OpenAPI file (openapi/atlas-api.yaml)
2. If we see any breaking changes without new resource version (
  - Review breaking changes listed in `Detect Breaking Changes` action
  - Checkout PR locally and run `make update-version`
  - Provide breaking changes infomation in generated `./releaser/breaking_changes/{release_version}.md` file
  - Push your changes directly to the automation PR. 
3. If we have major version release request feedback from additional reviewer if possible.
4. Merge PR into main branch 
5. After merge automated release process will be triggered.

### CODE REVIEW

**Comment by wtrocki** [comment]
Context: ongoing issue is preventing us from fetching openapi using URL. 
To unblock various teams I have created manual PR containing bot updates.

**Comment by gssbzn** [comment]
> Added transformation that removes pretty/envelope. Enables us to use schema without sdk filter (we can consider removing the filter from url for simplicity

Not sure about the why of this change?

**Comment by wtrocki** [comment]
> Not sure about the why of this change?

We cannot rely on the URL to fetch api right now. Only URL-based fetch method has `sdk` filter. Since URL right now has the issue I needed to use open API file from doc. 

In normal operation, this transformation has no effect, but when we use open API that is unfiltered (from docs), it will save us a lot of manual work to remove invalid parameters from OpenAPI.

Should I remove it from the PR?

**Comment by gssbzn** [comment]
>We cannot rely on the URL to fetch api right now

Why? and why are we preferring to fix downstream over fixing upstream?

**Comment by wtrocki** [comment]
Update:
We have jira for the fix upstream(CLOUDP-197116). This PR only regenerates open API in order to release SDK.

**Review by gssbzn — APPROVED** [review]
LGTM

**Pull request merged**
