### PR TITLE
CLOUDP-217493 - Arrays as pointers

### PR DESCRIPTION
**Pull request by wtrocki**
## Description

Refactor to make SDK use pointers for non-required arrays.  

Working on docs.

## Progress

- [x] Template change
- [x] Regenerated code

## Follow up PR 
- [ ] Documentation updates
- [ ] Usage in Atlas CLI
- [ ] Usage in CDK
Link to any related issue(s): CLOUDP-217493

## Testing

Run all the examples locally

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by wtrocki** [comment]
Decided to leave documentation separately once we know if PR does work for integrations and cli.

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Comment by wtrocki** [comment]
Just removed unneeded whitespaces

**Comment by wtrocki** [comment]
As a follow-up up we need to prepare release notes, docs, and tests. Merged PR to make it easier to consume these changes as part of the dev preview.

**Pull request merged**
